#本脚本由何友珏（info[at]heyoujue.com）编写，主要用于Emalyse导出的ema数据处理。
#This script was writen by Youjue He(info[at]heyoujue.com), it is only applied to the EMA data exported by Emalyse.
#请将wav TextGrid txt 放在同一文件夹下，且不能有其他文件。
#make sure that wav TextGrid txt files have the same names and are in the same folders. The folders should not contain other txt files.



library(tidyverse)
setwd("~/REMA")#The folders contain wav TextGrid txt files.
samplepoint<- read.table('./script/all_durationratio.txt')#import all_durationratio files which is generated by timeration.praat script.
slp <- samplepoint %>% 
  mutate(sound = str_sub(samplepoint$V1, -8,-5))

emalist<- list.files("./example",pattern = "txt",full.names = T)
emadata = data.frame(matrix(
  vector(), 0, 12, dimnames=list(c(), c('Ch4_X', 'Ch5_X','Ch6_X','Ch7_X','Ch8_X','Ch9_X','Ch4_Z', 'Ch5_Z','Ch6_Z','Ch7_Z','Ch8_Z','Ch9_Z'))),stringsAsFactors=T)
for (filename in emalist){
  df<- read.table(filename,header = T)
  #选取唇，齿龈，和舌的数据 select sensor channels
  df<-select(df,starts_with(c('Ch4', 'Ch5','Ch6','Ch7','Ch8','Ch9')))
  df<-select(df,ends_with(c('X','Z')))

  #合并表
  df<-df %>% 
    mutate(sound = str_sub(filename,-8,-5))
  
  df<-merge(df, slp)
  #选取标注的时间段
  samplerate=200 #输入ema的采样率 set EMA sampling rate
  slppnt<-nrow(df)
  start.time<- round(df$V3*samplerate)
  end.time<- round(df$V4*samplerate)
  df<-df[start.time:end.time,]
  rownames(df)<-1:nrow(df)
  #重新采样10个点 set he resampling rate.
  resamplingrate = 11
  df<-df[c(seq(1,nrow(df),length.out=resamplingrate)),]
  #添加时间点顺序
  df<-df %>% 
    mutate(timepoint=1:nrow(df))
  #长宽数据转换
  #原始数据最好用某些分割符号分开。例如这里的数据是Ch（通道序号）_（座标）。那么r在自动提取变量的时候，会将_之前的看作一个变量，与names_to中的第一个变量名相匹配。但是由于names_to中的第二个变量是'.value'，意思是_之后的所有不完全相同的字段，都会单独赋予一个变量名。
  df<-pivot_longer(df,cols = 2:13,names_to=c('Channel','.value'),names_sep   ="_" ,values_drop_na = TRUE)

  #粘合数据
  emadata<-rbind(emadata,df)
}

 #比较元音并作图 Comparison vowel [i] and [a]

vowelia<-subset(emadata, emadata$V2 == "i"|emadata$V2 == "a")
vowelia<-subset(vowelia, vowelia$Channel == "Ch4"|vowelia$Channel == "Ch5"|vowelia$Channel == "Ch6")

#散点图 scatter
scatter<-ggplot(vowelia, aes(X,Z, group= V2, color = V2))+geom_point()+scale_x_reverse()+annotate('text',x=70,y=-75,label="Anterior")+geom_line(linewidth=1,linetype = "dashed")+ylab(label = "coronal plane")+xlab(label = "sagittal plane")+scale_color_discrete(name = "vowel", labels=c("a","u","i"))
ggsave("./script/scatter.png", dpi=600)

#平均值图 average plot
avei<-aggregate(cbind(X,Z) ~V2+ Channel, data= vowelia, mean)
average<-ggplot(avei, aes(X,Z, group= V2, color = V2))+geom_point(size=3)+scale_x_reverse()+annotate('text',x=70,y=-75,label="Anterior")+geom_line(linewidth=1,linetype = "dashed")+ylab(label = "coronal plane")+xlab(label = "sagittal plane")+scale_color_discrete(name = "vowel", labels=c("a","u","i"))


ggsave("./script/average.png", dpi=600)


